import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import {
  COMPACT_PHONE_MAX_WIDTH,
  COMPACT_SHELL_MEDIA_QUERY,
  COMPACT_TOUCH_MAX_WIDTH,
  SHELL_DESIGN_HEIGHT,
  SHELL_DESIGN_WIDTH,
  SHELL_MIN_UI_SCALE,
  calculateShellViewport,
  expandedMainWidthForShell,
  shouldAutoCollapseOpsRail,
  shouldForceCompactShell,
  shouldUseCompactShell,
} from '../src/games/stardew/responsive-layout.ts'
import { playerAuthPasswordError } from '../src/games/stardew/player-auth-password.ts'

function readTextFile(url: URL): string {
  return readFileSync(url, 'utf8').replace(/\r\n?/g, '\n')
}

const installDownloadIcon = readFileSync(new URL('../public/assets/stardew/ui/install/icon_install_step_download_image2_regen.png', import.meta.url))
assert.equal(installDownloadIcon.subarray(0, 8).toString('hex'), '89504e470d0a1a0a', 'download icon must be PNG')
assert.equal(installDownloadIcon.readUInt32BE(16), 72, 'download icon width')
assert.equal(installDownloadIcon.readUInt32BE(20), 72, 'download icon height')
assert.equal(installDownloadIcon[25], 6, 'download icon must keep RGBA transparency')

function closeTo(actual: number, expected: number, message: string, tolerance = 1e-7): void {
  assert.ok(
    Math.abs(actual - expected) <= tolerance,
    `${message}: expected ${expected}, received ${actual}`,
  )
}

function assertValidLayout(width: number, height: number): void {
  const layout = calculateShellViewport(width, height)
  assert.ok(Number.isFinite(layout.scale) && layout.scale >= SHELL_MIN_UI_SCALE)
  assert.ok(Number.isFinite(layout.layoutWidth) && layout.layoutWidth > 0)
  assert.ok(Number.isFinite(layout.layoutHeight) && layout.layoutHeight > 0)
  closeTo(layout.layoutWidth * layout.scale, width, `${width}×${height} visual width`)
  closeTo(layout.layoutHeight * layout.scale, height, `${width}×${height} visual height`)

  if (layout.scale > SHELL_MIN_UI_SCALE + Number.EPSILON) {
    assert.ok(
      Math.abs(layout.layoutWidth - SHELL_DESIGN_WIDTH) <= 1e-7 ||
        Math.abs(layout.layoutHeight - SHELL_DESIGN_HEIGHT) <= 1e-7,
      `${width}×${height} must remain anchored to one design edge above the minimum scale`,
    )
  }
}

assert.equal(SHELL_DESIGN_WIDTH, 1536)
assert.equal(SHELL_DESIGN_HEIGHT, 1024)
assert.equal(SHELL_MIN_UI_SCALE, 0.72)
assert.equal(COMPACT_PHONE_MAX_WIDTH, 768)
assert.equal(COMPACT_TOUCH_MAX_WIDTH, 1366)
assert.match(COMPACT_SHELL_MEDIA_QUERY, /max-width: 768px/)
assert.match(COMPACT_SHELL_MEDIA_QUERY, /hover: none/)
assert.match(COMPACT_SHELL_MEDIA_QUERY, /pointer: coarse/)
assert.match(COMPACT_SHELL_MEDIA_QUERY, /max-width: 1366px/)
assert.equal(shouldForceCompactShell('?shell=mobile'), true)
assert.equal(shouldForceCompactShell('?playerId=123&shell=mobile'), true)
assert.equal(shouldForceCompactShell('?shell=desktop'), false)
assert.equal(shouldForceCompactShell('?shell=MOBILE'), false)
assert.equal(shouldForceCompactShell(''), false)

for (const [width, hoverNone, pointerCoarse, expected] of [
  [767, false, false, true],
  [768, false, false, true],
  [769, false, false, false],
  [769, true, true, true],
  [1366, true, true, true],
  [1366, false, true, false],
  [1366, true, false, false],
  [1367, true, true, false],
  [Number.NaN, true, true, false],
] as const) {
  assert.equal(
    shouldUseCompactShell(width, hoverNone, pointerCoarse),
    expected,
    `compact-shell capability tuple ${String(width)}/${hoverNone}/${pointerCoarse}`,
  )
}

const sweepHeights = [240, 320, 360, 390, 480, 568, 600, 720, 768, 844, 900, 1024, 1080, 1180, 1440, 2160]
for (let width = 280; width <= 3840; width += 1) {
  for (const height of sweepHeights) assertValidLayout(width, height)
}

for (const [width, height] of [
  [280, 653],
  [319, 568],
  [320, 568],
  [640, 480],
  [641, 480],
  [720, 600],
  [721, 600],
  [768, 1024],
  [769, 1024],
  [1105, 737],
  [1106, 738],
  [1366, 500],
  [1367, 500],
  [1920, 500],
  [2560, 720],
  [3840, 2160],
  [5120, 1440],
  [7680, 4320],
] as const) {
  assertValidLayout(width, height)
}

closeTo(calculateShellViewport(1105, 900).scale, 0.72, 'minimum scale below width threshold')
assert.ok(calculateShellViewport(1106, 738).scale > 0.72)
closeTo(calculateShellViewport(1366, 768).scale, 0.75, 'height-limited desktop scale')
closeTo(calculateShellViewport(1920, 1080).scale, 1080 / 1024, 'large desktop scale')

for (const [width, height] of [
  [Number.NaN, 0],
  [Number.POSITIVE_INFINITY, 844],
  [390, Number.NEGATIVE_INFINITY],
  [-1, -1],
] as const) {
  const layout = calculateShellViewport(width, height)
  assert.ok(Number.isFinite(layout.scale) && layout.scale >= SHELL_MIN_UI_SCALE)
  assert.ok(Number.isFinite(layout.layoutWidth) && layout.layoutWidth > 0)
  assert.ok(Number.isFinite(layout.layoutHeight) && layout.layoutHeight > 0)
}

assert.equal(shouldAutoCollapseOpsRail(720, 600, false), false)
assert.ok(Number.isFinite(expandedMainWidthForShell(721, 600)))
const freshExpandWidth = Array.from({ length: 1600 }, (_, index) => 721 + index).find(
  (width) => !shouldAutoCollapseOpsRail(width, 768, false),
)
const collapsedExpandWidth = Array.from({ length: 1600 }, (_, index) => 721 + index).find(
  (width) => !shouldAutoCollapseOpsRail(width, 768, true),
)
assert.ok(freshExpandWidth != null && collapsedExpandWidth != null)
assert.ok(collapsedExpandWidth > freshExpandWidth, 'ops rail must retain a real hysteresis band')

const shellCss = readTextFile(new URL('../src/games/stardew/StardewPanel.css', import.meta.url))
const panelSource = readTextFile(new URL('../src/games/stardew/StardewPanel.tsx', import.meta.url))
const instanceIdSource = readTextFile(new URL('../src/instance-id.ts', import.meta.url))
const appCss = readTextFile(new URL('../src/App.css', import.meta.url))
const authCardCss = readTextFile(new URL('../src/core/AuthCard.css', import.meta.url))
const compactShellCss = readTextFile(new URL('../src/games/stardew/StardewMobileShell.css', import.meta.url))
const compactShellSource = readTextFile(new URL('../src/games/stardew/StardewMobileShell.tsx', import.meta.url))
const updateDialogCss = readTextFile(new URL('../src/games/stardew/UpdateDetailsDialog.css', import.meta.url))
const panelUpdateCss = readTextFile(new URL('../src/games/stardew/PanelUpdateProvider.css', import.meta.url))
const mobilePlayersCss = readTextFile(new URL('../src/games/stardew/mobile/MobilePlayersPage.css', import.meta.url))
const newGameCreatorCss = readTextFile(new URL('../src/games/stardew/NewGameCreator.css', import.meta.url))
const savesPageCss = readTextFile(new URL('../src/games/stardew/pages/SavesPage.css', import.meta.url))
const modsPageCss = readTextFile(new URL('../src/games/stardew/pages/ModsPage.css', import.meta.url))
const modsPageSource = readTextFile(new URL('../src/games/stardew/pages/ModsPage.tsx', import.meta.url))
const diagnosticsPageCss = readTextFile(new URL('../src/games/stardew/pages/DiagnosticsPage.css', import.meta.url))
const diagnosticsPageSource = readTextFile(new URL('../src/games/stardew/pages/DiagnosticsPage.tsx', import.meta.url))
const modalPortalSource = readTextFile(new URL('../src/core/ModalPortal.tsx', import.meta.url))
const playersPageCss = readTextFile(new URL('../src/games/stardew/pages/PlayersPage.css', import.meta.url))
const playersPageSource = readTextFile(new URL('../src/games/stardew/pages/PlayersPage.tsx', import.meta.url))
const savesSectionSource = readTextFile(new URL('../src/games/stardew/SavesSection.tsx', import.meta.url))
const settingsPageSource = readTextFile(new URL('../src/games/stardew/pages/SettingsPage.tsx', import.meta.url))
const jobsLogsPageSource = readTextFile(new URL('../src/games/stardew/pages/JobsLogsPage.tsx', import.meta.url))
const apiSource = readTextFile(new URL('../src/api.ts', import.meta.url))
const dashboardDataSource = readTextFile(new URL('../src/games/stardew/useStardewDashboardData.ts', import.meta.url))
const overviewPageSource = readTextFile(new URL('../src/games/stardew/pages/OverviewPage.tsx', import.meta.url))
const serverSummarySource = readTextFile(new URL('../src/games/stardew/ServerSummaryCard.tsx', import.meta.url))
const inviteCardSource = readTextFile(new URL('../src/games/stardew/InviteCodeCard.tsx', import.meta.url))
const steamInviteStateSource = readTextFile(new URL('../src/games/stardew/steam-invite-state.ts', import.meta.url))
const lanDirectConnectSource = readTextFile(new URL('../src/games/stardew/LanDirectConnectCard.tsx', import.meta.url))
const gameLibraryCss = readTextFile(new URL('../src/games/GameLibrary.css', import.meta.url))
const gameLibrarySource = readTextFile(new URL('../src/games/GameLibrary.tsx', import.meta.url))
const gameInstallRailSource = readTextFile(new URL('../src/games/GameInstallRail.tsx', import.meta.url))
const installProgressPresentationSource = readTextFile(new URL('../src/games/stardew/install-progress-presentation.ts', import.meta.url))
const mobileHomePageSource = readTextFile(new URL('../src/games/stardew/mobile/MobileHomePage.tsx', import.meta.url))
const appSource = readTextFile(new URL('../src/App.tsx', import.meta.url))
const appRoutesSource = readTextFile(new URL('../src/app-routes.ts', import.meta.url))
const mobileControlPageSource = readTextFile(new URL('../src/games/stardew/mobile/MobileControlPage.tsx', import.meta.url))
const serverControlPageSource = readTextFile(new URL('../src/games/stardew/pages/ServerControlPage.tsx', import.meta.url))
const playerAuthDialogSource = readTextFile(new URL('../src/games/stardew/PlayerAuthSettingsDialog.tsx', import.meta.url))
const playerAuthDialogCss = readTextFile(new URL('../src/games/stardew/PlayerAuthSettingsDialog.css', import.meta.url))
const lifecycleActionsSource = readTextFile(new URL('../src/games/stardew/useStardewLifecycleActions.ts', import.meta.url))
const mobileSavesPageSource = readTextFile(new URL('../src/games/stardew/mobile/MobileSavesPage.tsx', import.meta.url))
const stardewRoutesSource = readTextFile(new URL('../src/games/stardew/stardew-routes.ts', import.meta.url))
const qaSource = readTextFile(new URL('../src/qa-layout-main.tsx', import.meta.url))
assert.match(qaSource, /qaInstallJob = \{\s+id: qaInstallJobId,\s+type: 'stardew_install',\s+displayName: '安装星露谷物语',\s+status: INSTALL_QA === 'retry' \? 'failed' : 'running'/)
assert.match(qaSource, /const lifecycleJobs = qaLibraryLifecycleOperation \? \[\{\s+id: 'qa-library-lifecycle',\s+type: 'stardew_lifecycle',\s+operation: qaLibraryLifecycleOperation,\s+status: 'running'/)
const releaseWorkflow = readTextFile(new URL('../../.github/workflows/release.yml', import.meta.url))
const releaseCandidateWorkflow = readTextFile(new URL('../../.github/workflows/release-candidate.yml', import.meta.url))
const releaseAfterCandidateWorkflow = readTextFile(new URL('../../.github/workflows/release-after-candidate.yml', import.meta.url))
const releaseGates = readTextFile(new URL('../../scripts/run-release-gates.sh', import.meta.url))
const releaseCandidateScript = readTextFile(new URL('../../scripts/release-candidate.sh', import.meta.url))
const releaseUpgradeE2E = readTextFile(new URL('../../scripts/tests/test_release_candidate_upgrade.sh', import.meta.url))
const releaseMatrixValidator = readTextFile(new URL('../../scripts/validate-release-matrix.sh', import.meta.url))
const releaseMatrixTests = readTextFile(new URL('../../scripts/tests/test_release_matrix.sh', import.meta.url))
const compatibilityWorkflow = readTextFile(new URL('../../.github/workflows/compatibility-matrix.yml', import.meta.url))

assert.doesNotMatch(shellCss, /100(?:vw|vh|dvh)\s*\/\s*var\(--sd-design/)
assert.doesNotMatch(shellCss, /--sd-ui-fluid-scale/)
assert.doesNotMatch(shellCss, /\/\s*var\(--sd-ui-scale\)/)
assert.match(shellCss, /width:\s*var\(--sd-shell-layout-width\)/)
assert.match(shellCss, /height:\s*var\(--sd-shell-layout-height\)/)
assert.match(shellCss, /transform:\s*scale\(var\(--sd-ui-scale\)\)/)
assert.match(shellCss, /touch-action:\s*pan-x pan-y pinch-zoom/)
assert.match(shellCss, /\.sd-opsrail-stack\s*{[^}]*overflow-y:\s*auto/s)
assert.doesNotMatch(appCss, /:has\(\.sd-shell\)/)
assert.match(appCss, /body\s*{[^}]*min-width:\s*280px/s)
assert.match(appCss, /#root\.sd-desktop-shell-mounted/)
assert.match(appCss, /#root\.sd-mobile-shell-mounted/)
assert.match(appCss, /max-aspect-ratio:\s*8\s*\/\s*5/)
assert.match(appCss, /min-aspect-ratio:\s*5\s*\/\s*2/)
assert.match(authCardCss, /\.sd-auth-shell\.sd-auth-shell--compact\s*\{[^}]*min-height:\s*100dvh/s)
assert.match(authCardCss, /\.sd-auth-card\s*\{[^}]*width:\s*min\(360px,\s*100%\)/s)
assert.match(shellCss, /\.sd-shell-viewport\s*{[^}]*overflow:\s*hidden/s)
assert.match(shellCss, /\.sd-shell-viewport\s*{[^}]*overflow:\s*clip/s)
assert.match(panelSource, /lockViewportOrigin/)
assert.match(compactShellCss, /padding-left:\s*env\(safe-area-inset-left/)
assert.match(compactShellCss, /padding-right:\s*env\(safe-area-inset-right/)
assert.match(compactShellCss, /touch-action:\s*pan-x pan-y pinch-zoom/)
assert.match(compactShellCss, /font-size:\s*16px/)
assert.match(compactShellCss, /\.sd-mshell-update\s*{[^}]*min-height:\s*44px/s)
assert.doesNotMatch(compactShellCss, /--sd-mobile-main-frame-edge-thickness\)\s*\/\s*2/)
assert.match(updateDialogCss, /\.sd-update-close\s*{[^}]*width:\s*44px;[^}]*height:\s*44px/s)
assert.match(updateDialogCss, /\.sd-update-actions a,\s*\.sd-update-actions button\s*{[^}]*min-height:\s*44px/s)
assert.match(updateDialogCss, /overscroll-behavior:\s*contain/)
assert.match(panelUpdateCss, /@media\s*\(max-width:\s*560px\)[\s\S]*?safe-area-inset-left/)
assert.match(mobilePlayersCss, /\.sd-mplay-player-actions\s*{[^}]*max-width:\s*100%/s)
assert.match(mobilePlayersCss, /\.sd-mplay-confirm-dialog\s*{[^}]*max-height:\s*calc\(100dvh - 32px\)/s)
assert.match(shellCss, /\.sd-confirm-dialog\s*{[^}]*box-sizing:\s*border-box/s)
assert.match(shellCss, /\.sd-confirm-dialog\s*{[^}]*max-height:\s*min\(90vh,\s*100%\)/s)
assert.match(savesPageCss, /\.sd-saves-modal-card\s*{[^}]*box-sizing:\s*border-box/s)
assert.match(savesPageCss, /\.sd-saves-modal-card\s*{[^}]*max-height:\s*min\(90vh,\s*100%\)/s)
assert.match(savesPageCss, /\.sd-saves-modal-card-wide\s*{[^}]*container-name:\s*ngc-modal[^}]*container-type:\s*inline-size/s)
assert.match(apiSource, /export function getLatestJobLogs/)
assert.match(apiSource, /params\.set\('latest', 'true'\)/)
assert.match(dashboardDataSource, /getLatestJobLogs\(jobId, 200\)/)
assert.match(dashboardDataSource, /if \(!steamInviteEnabledRef\.current\) \{[\s\S]*?setInviteCodeStatus\('disabled'\)[\s\S]*?return/)
assert.doesNotMatch(dashboardDataSource, /Promise\.allSettled\(\[[\s\S]{0,500}refreshInviteCode\(\)/)
assert.match(dashboardDataSource, /shouldPollSteamInvite\([\s\S]*?inviteCodeStatus/)
assert.match(dashboardDataSource, /STEAM_INVITE_POLL_INTERVAL_MS = 5_000/)
assert.match(dashboardDataSource, /STEAM_INVITE_POLL_MAX_ATTEMPTS = 125/)
assert.match(dashboardDataSource, /const shouldResetRuntimeGeneration = shouldRestartSteamInvitePolling\([\s\S]*?previousRuntimeState[\s\S]*?s\.state[\s\S]*?invitePollLastStatusRef\.current/)
assert.match(dashboardDataSource, /invitePollBudgetExhaustedRef\.current = true[\s\S]*?setInvitePollRequested\(false\)/)
assert.match(dashboardDataSource, /runtimeMayStillBeWarming[\s\S]*?const failureStatus = runtimeMayStillBeWarming \? 'generating' : 'auth_unavailable'[\s\S]*?setInviteCodeStatus\(failureStatus\)/)
assert.match(dashboardDataSource, /const shouldContinuePolling = shouldPollSteamInvite\([\s\S]*?setInvitePollRequested\(shouldContinuePolling\)/)
assert.match(dashboardDataSource, /setInvitePollRequested\(runtimeMayStillBeWarming\)/)
assert.match(dashboardDataSource, /if \(invitePollLastStatusRef\.current === 'auth_unavailable'\) return/)
assert.match(dashboardDataSource, /const inviteRequestGeneration = \+\+inviteRequestGenerationRef\.current/)
assert.match(dashboardDataSource, /isCurrentSteamInviteRequest\([\s\S]*?inviteRequestGenerationRef\.current[\s\S]*?steamInviteEnabledRef\.current/)
assert.match(dashboardDataSource, /instanceStateRequestGenerationRef\.current[\s\S]*?stateRequestGeneration !== instanceStateRequestGenerationRef\.current/)
assert.match(dashboardDataSource, /const inviteProjectionGeneration = \+\+inviteProjectionGenerationRef\.current/)
assert.match(dashboardDataSource, /const canProjectInvite = isCurrentSteamInviteProjection\([\s\S]*?preserveSteamInviteProjection\([\s\S]*?if \(!canProjectInvite\) return/)
assert.match(dashboardDataSource, /if \(shouldResetRuntimeGeneration\) \{[\s\S]*?invitePollAttemptsRef\.current = 0[\s\S]*?invitePollBudgetExhaustedRef\.current = false[\s\S]*?!canProjectInvite && shouldResumeSteamInviteAfterRuntimeReset\([\s\S]*?setInviteCodeStatus\('generating'\)[\s\S]*?setInvitePollRequested\(true\)/)
assert.match(dashboardDataSource, /!isCurrentSteamInviteProjection\([\s\S]*?inviteProjectionGenerationRef\.current[\s\S]*?\)\) return/)
assert.match(dashboardDataSource, /steamInviteEnabledRef\.current = false[\s\S]*?steamInviteEnabled: false, inviteCode: ''[\s\S]*?setInviteCodeLoading\(false\)/)
assert.match(dashboardDataSource, /const clearInviteCode[\s\S]*?inviteProjectionGenerationRef\.current \+= 1[\s\S]*?const requestInviteCodeRefresh[\s\S]*?inviteProjectionGenerationRef\.current \+= 1/)
assert.match(dashboardDataSource, /const shouldStartPollingWithoutCurrentCode = shouldStartPolling && !inviteCodeRef\.current/)
assert.match(dashboardDataSource, /delayedJobRefreshRef\.current = window\.setTimeout\([\s\S]*?if \(!dashboardMountedRef\.current\) return/)
assert.match(dashboardDataSource, /dashboardMountedRef\.current = false[\s\S]*?clearTimeout\(delayedJobRefreshRef\.current\)/)
assert.match(dashboardDataSource, /await refreshInstanceState\(\)[\s\S]*?steamInviteEnabledRef\.current[\s\S]*?await refreshInviteCode\(\)/)
assert.match(dashboardDataSource, /const pollInviteCode = async \(\) => \{[\s\S]*?await refreshInstanceState\(\)[\s\S]*?if \(cancelled \|\| !steamInviteEnabledRef\.current\) return[\s\S]*?await refreshInviteCode\(\)/)
assert.match(dashboardDataSource, /const stateExposesInviteCode = s\.state === 'running'/)
assert.match(dashboardDataSource, /if \(!stateExposesInviteCode\) \{[\s\S]*?updateInviteCode\(null\)[\s\S]*?else if \(!recordedInviteCode\)/)
// The invite card must render even when Steam invites are not enabled yet. Gating
// it behind steamInviteEnabled hid the only entry point an admin had to enable the
// feature, which locked the card away permanently.
assert.match(overviewPageSource, /<LanDirectConnectCard dashboardData=\{dashboardData\} \/>\s*<InviteCodeCard instanceState=\{instanceState\}/)
assert.doesNotMatch(overviewPageSource, /steamInviteEnabled === true\s*&&\s*<InviteCodeCard/)
assert.match(serverSummarySource, /<LanDirectConnectCard dashboardData=\{dashboardData\} \/>\s*<InviteCodeCard/)
assert.doesNotMatch(serverSummarySource, /steamInviteEnabled === true\s*&&\s*<InviteCodeCard/)
// Same for the mobile invite row; the flag is now used only for the stop warning.
assert.match(mobileHomePageSource, /sd-mhome-invite-label">Steam 邀请码/)
assert.doesNotMatch(mobileHomePageSource, /steamInviteEnabled \? \(/)
assert.match(mobileHomePageSource, /局域网直连/)
assert.match(mobileHomePageSource, /const steamInviteEnabled = steamInviteIsEnabled\(instanceState\)/)
assert.match(mobileHomePageSource, /invite\.retryAuthorization && isAdmin \? \([\s\S]*?重新授权/)
assert.match(mobileHomePageSource, /invite\.retryAuthorization && !isAdmin[\s\S]*?授权异常，请联系管理员/)
assert.match(mobileHomePageSource, /\{inviteText\}/)
assert.match(mobileHomePageSource, /useSteamAuthLogin\(\{[\s\S]*?routeToPath\(route, options\)[\s\S]*?onUseDesktop\(\)/)
assert.match(mobileHomePageSource, /steamAuth\.requiresStop[\s\S]*?请先停止服务器，再重新完成 Steam 邀请码授权/)
assert.match(mobileHomePageSource, /const \[pendingStartupSawActiveJob, setPendingStartupSawActiveJob\] = useState\(false\)/)
assert.match(mobileHomePageSource, /pendingStartupAction && hasActiveLifecycleJob[\s\S]*?setPendingStartupSawActiveJob\(true\)/)
assert.match(mobileHomePageSource, /shouldClearPendingStartupAction\(\{[\s\S]*?sawActiveLifecycleJob: pendingStartupSawActiveJob[\s\S]*?setPendingStartupAction\(null\)[\s\S]*?setPendingStartupSawActiveJob\(false\)/)
// The card must never hide itself just because invites are not enabled yet: that
// self-lock was exactly why an administrator had no reachable way to turn the
// feature on. It now renders the enable entry instead.
assert.doesNotMatch(inviteCardSource, /if \(!enabled\) return null/)
assert.match(inviteCardSource, /const needsEnable = presentation\.needsEnable/)
assert.match(inviteCardSource, /needsEnable \? \([\s\S]*?canManageSteamInvite \? \(/)
assert.match(inviteCardSource, /授权尚未就绪|重新授权/)
assert.match(inviteCardSource, /steamInvitePresentation\([\s\S]*?instanceState\?\.state/)
assert.match(mobileHomePageSource, /steamInvitePresentation\([\s\S]*?instanceState\?\.state/)
assert.match(inviteCardSource, /steamInvitePresentation\([\s\S]*?dashboardData\.inviteCodeRefreshing/)
assert.match(mobileHomePageSource, /steamInvitePresentation\([\s\S]*?dashboardData\.inviteCodeRefreshing/)
assert.match(overviewPageSource, /confirmAction === 'stop'[\s\S]*?instanceState\?\.steamInviteEnabled === true[\s\S]*?Steam 邀请码将失效[\s\S]*?停止服务器将断开所有玩家连接。/)
assert.match(serverControlPageSource, /confirmAction === 'stop'[\s\S]*?instanceState\?\.steamInviteEnabled === true[\s\S]*?Steam 邀请码将立即失效[\s\S]*?停止服务器将断开所有在线玩家的连接。此操作不可撤销/)
assert.match(mobileHomePageSource, /steamInviteEnabled[\s\S]*?Steam 邀请码将失效[\s\S]*?停止服务器将断开所有玩家连接。/)
assert.match(steamInviteStateSource, /if \(status === 'auth_unavailable'\)[\s\S]*?Auth 异常（直连仍可用）/)
assert.match(steamInviteStateSource, /polling && error && status === 'generating'[\s\S]*?runtimeState === 'starting'[\s\S]*?runtimeState === 'running'/)
assert.doesNotMatch(steamInviteStateSource, /state\.state === 'starting' && status === 'auth_unavailable'/)
assert.match(steamInviteStateSource, /text: '等待中…'/)
assert.match(lanDirectConnectSource, /局域网直连/)
assert.match(gameLibrarySource, /setCatalog\(\{ items, loading: false, error: null \}\)/)
assert.match(gameLibrarySource, /getInstanceDirectConnect\(instanceId\)/)
assert.match(gameLibrarySource, /getInstanceState\(item\.instance\.id\)/)
assert.doesNotMatch(gameLibrarySource, /Promise\.all\([^)]*getInstanceState/)
const targetedWorldRefresh = gameLibrarySource.match(/const refreshInstance = useCallback\([\s\S]*?\n  \}, \[\]\)/)
assert.ok(targetedWorldRefresh, 'world lifecycle polling must expose a targeted instance refresh')
assert.match(targetedWorldRefresh[0], /getInstanceState\(instanceId\)/)
assert.match(targetedWorldRefresh[0], /getJobs\(\)/)
assert.doesNotMatch(targetedWorldRefresh[0], /getInstanceDirectConnect/)
assert.match(gameLibrarySource, /window\.setInterval\(\(\) => onRefresh\(item\.instance\.id\), 1_500\)/)
assert.doesNotMatch(gameLibrarySource, /window\.setInterval\(onRefresh, 1_500\)/)
assert.match(gameLibrarySource, /onRefresh=\{catalog\.refreshInstance\}/)
assert.match(gameLibrarySource, /gameCardNavigationIndex\(currentIndex, GAME_CARD_ENABLED, intent\)/)
assert.match(gameLibrarySource, /event\.key === 'Enter' \|\| event\.key === ' '/)
assert.match(gameLibrarySource, /prefers-reduced-motion[\s\S]*?scrollIntoView\(\{[\s\S]*?inline: 'nearest'/)
assert.match(gameLibrarySource, /if \(railOpen\) return[\s\S]*?const selectedCard = cardRefs\.current\[selectedIndex\][\s\S]*?\}, \[railOpen, selectedIndex\]\)/)
assert.match(gameLibrarySource, /onPointerMove=\{handleTouchMove\}/)
assert.match(gameLibrarySource, /suppressClickUntilRef\.current = performance\.now\(\) \+ 450/)
assert.match(gameLibrarySource, /installOpen[\s\S]*?`星露谷物语，\$\{installProgressLabel\}，点击收起安装`[\s\S]*?worldsOpen[\s\S]*?`星露谷物语，\$\{installCard\.label\}，点击收起世界`/)
assert.match(gameLibrarySource, /aria-label="其他游戏，暂未接入"[\s\S]*?disabled/)
assert.match(gameLibrarySource, /<strong>ANXI PANEL<\/strong>/)
assert.doesNotMatch(gameLibrarySource, /自托管游戏中心|className="game-hub-nav"/)
assert.doesNotMatch(gameLibrarySource, /title="选择要管理的游戏"|eyebrow="游戏库"|game-picker-hints/)
assert.match(gameLibrarySource, /className="game-hub-theme-toggle"[\s\S]*?切换到静夜背景[\s\S]*?切换到暖昼背景/)
assert.doesNotMatch(gameLibrarySource, /game-background-switch|aria-label="游戏库背景"/)
assert.match(gameLibrarySource, /aria-disabled=\{installCard\.actionDisabled\}[\s\S]*?aria-expanded=\{railOpen && !worldsClosing\}[\s\S]*?aria-busy=\{worldsClosing\}/)
assert.match(gameLibrarySource, /const WORLD_RAIL_OPEN_MS = 360[\s\S]*?const WORLD_RAIL_CLOSE_MS = 360/)
assert.match(gameLibrarySource, /setWorldClosePhase\('closing'\)[\s\S]*?window\.setTimeout\(\(\) => \{[\s\S]*?completeWorldClose\(\)[\s\S]*?WORLD_RAIL_CLOSE_MS/)
assert.doesNotMatch(gameLibrarySource, /hiding-worlds|recentering|WORLD_RAIL_HIDE_MS|WORLD_RAIL_RECENTER_MS/)
assert.match(gameLibrarySource, /const completeWorldClose = useCallback\(\(\) => \{[\s\S]*?onNavigate\('\/games'\)[\s\S]*?cardRefs\.current\[0\]\?\.focus/)
assert.match(gameLibrarySource, /event\.key !== 'Escape'[\s\S]*?if \(createWorldOpen\) \{[\s\S]*?onNavigate\('\/games\/stardew'\)[\s\S]*?closeWorlds\(\)/)
assert.match(gameLibrarySource, /<WorldRail[\s\S]*?catalog=\{catalog\}[\s\S]*?user=\{user\}[\s\S]*?open=\{railOpen\}[\s\S]*?installOpen=\{installOpen\}[\s\S]*?createWorldOpen=\{createWorldOpen\}[\s\S]*?closePhase=\{worldClosePhase\}/)
assert.match(gameLibrarySource, /id="stardew-detail-rail"[\s\S]*?className=\{`game-world-rail[\s\S]*?closePhase === 'closing'[\s\S]*?style=\{\{ width: open && closePhase === 'idle' \? contentWidth : 0 \}\}[\s\S]*?aria-hidden=\{!open \|\| closePhase !== 'idle'\}[\s\S]*?inert=\{!open \|\| closePhase !== 'idle'\}/)
assert.match(gameLibrarySource, /new ResizeObserver\(measure\)/)
assert.match(gameLibrarySource, /const animatePickerTo = \(targetLeft: number, duration: number, easing:[\s\S]*?picker\.scrollLeft = startLeft \+ distance \* easing\(progress\)[\s\S]*?window\.requestAnimationFrame\(animate\)/)
assert.match(gameLibrarySource, /const scrollPickerToStart = \(\) => \{[\s\S]*?WORLD_RAIL_CLOSE_MS[\s\S]*?progress \* progress \* \(3 - 2 \* progress\)/)
assert.match(gameLibrarySource, /const scrollPickerOpenTo = \(targetLeft: number\) => \{[\s\S]*?WORLD_RAIL_OPEN_MS[\s\S]*?progress \* progress \* \(3 - 2 \* progress\)/)
assert.match(gameLibrarySource, /if \(closePhase === 'closing'\) \{[\s\S]*?scrollPickerToStart\(\)/)
assert.match(gameLibrarySource, /const clusterStart = primaryRect\.left - pickerRect\.left \+ picker\.scrollLeft[\s\S]*?const fullClusterWidth = primary\.offsetWidth \+ contentWidth/)
assert.match(gameLibrarySource, /fullClusterWidth <= picker\.clientWidth[\s\S]*?leadingClusterWidth <= picker\.clientWidth[\s\S]*?const clusterCenter = clusterStart \+ clusterWidth \/ 2[\s\S]*?scrollPickerOpenTo\(Math\.max\(0, clusterCenter - picker\.clientWidth \/ 2\)\)/)
assert.match(gameLibrarySource, /const narrowViewport = window\.matchMedia\('\(max-width: 700px\)'\)\.matches[\s\S]*?const startLeft = picker\.scrollLeft[\s\S]*?behavior: 'auto'[\s\S]*?inline: narrowViewport \? 'start' : 'nearest'[\s\S]*?const targetLeft = picker\.scrollLeft[\s\S]*?picker\.scrollLeft = startLeft[\s\S]*?scrollPickerOpenTo\(targetLeft\)/)
assert.match(gameLibrarySource, /const scheduleAlignment = \(\) => \{[\s\S]*?window\.setTimeout\(alignRail, 0\)[\s\S]*?alignRail\(\)/)
assert.match(gameLibrarySource, /const createForm = content\.querySelector<HTMLElement>\('\.world-create-card--form'\)[\s\S]*?createWorldOpen && createForm[\s\S]*?const formStart = rail\.offsetLeft \+ createForm\.offsetLeft[\s\S]*?const formEnd = formStart \+ createForm\.offsetWidth[\s\S]*?formEnd - picker\.clientWidth \+ inset[\s\S]*?scrollPickerOpenTo\(targetLeft\)/)
assert.doesNotMatch(gameLibrarySource, /ModalPortal|world-chooser-backdrop|world-chooser-title/)
assert.match(gameLibrarySource, /<small>加入地址<\/small>/)
assert.doesNotMatch(gameLibrarySource, /更新时间/)
assert.match(gameLibrarySource, /function WorldChoiceCard[\s\S]*?copyText\(copyValue\)/)
assert.match(gameLibrarySource, /className="world-choice-open"[\s\S]*?className=\{`world-copy-button/)
assert.match(gameLibrarySource, /startInstance\(item\.instance\.id\)[\s\S]*?stopInstance\(item\.instance\.id\)/)
assert.match(gameLibrarySource, /world-lifecycle-button--\$\{lifecycle\.tone\}[\s\S]*?aria-busy=\{lifecycle\.busy\}/)
assert.match(gameLibrarySource, /shouldClearPendingStartupAction\([\s\S]*?pendingStartupSawActiveJob/)
assert.match(gameLibrarySource, /canCreateWorld\(user\.role\) \? createWorldOpen \? \([\s\S]*?onNavigate\('\/games\/stardew\/new'\)/)
assert.match(gameLibrarySource, /function InlineWorldCreateCard[\s\S]*?createInstance\(stardewCreateInstanceRequest\(name\)\)[\s\S]*?routeToPath\('saves', undefined, response\.instance\.id\)/)
assert.match(gameLibrarySource, /nameInputRef\.current\?\.focus\(\{ preventScroll: true \}\)[\s\S]*?<strong>请输入世界名称<\/strong>[\s\S]*?ref=\{nameInputRef\}[\s\S]*?maxLength=\{40\}[\s\S]*?创建世界/)
assert.match(gameLibrarySource, /canCreateWorld\(user\.role\) \? createWorldOpen \? \([\s\S]*?<InlineWorldCreateCard onNavigate=\{onNavigate\} \/>[\s\S]*?className="world-create-card"/)
assert.match(gameLibrarySource, /previousCreateWorldOpenRef\.current && !createWorldOpen[\s\S]*?createButtonRef\.current\?\.focus/)
assert.match(gameLibrarySource, /createWorldOpen && !canCreateWorld\(user\.role\)[\s\S]*?onNavigate\('\/games\/stardew', true\)/)
assert.doesNotMatch(gameLibrarySource, /export function StardewNewWorldPage|new-world-layout|new-world-form|new-world-receipt/)
assert.doesNotMatch(gameLibrarySource, /world-create-note|新建世界需要管理员权限/)
assert.doesNotMatch(gameLibrarySource, /game-action-dock|饥荒联机版|Minecraft/)
assert.match(gameLibrarySource, /GAME_LIBRARY_BACKGROUND_STORAGE_KEY = 'anxi\.game-library-background\.v1'/)
assert.match(gameLibrarySource, /GAME_LIBRARY_BACKGROUND_MANUAL_UNTIL_STORAGE_KEY = 'anxi\.game-library-background-manual-until\.v1'/)
assert.match(gameLibrarySource, /const automaticBackground = gameLibraryBackgroundForDate\(now\)/)
assert.match(gameLibrarySource, /const synchronizeBackgroundWithClock = \(\) => \{[\s\S]*?gameLibraryNextBackgroundBoundary\(now\)[\s\S]*?window\.setTimeout\(synchronizeBackgroundWithClock, delay\)/)
assert.match(gameLibrarySource, /const manualUntil = gameLibraryNextBackgroundBoundary\(new Date\(\)\)[\s\S]*?setBackgroundSelection\(\{ background: nextBackground, manualUntil \}\)/)
assert.match(gameLibraryCss, /\.game-picker\s*\{[^}]*overflow-x:\s*auto[^}]*scroll-snap-type:\s*x mandatory/s)
assert.match(gameLibraryCss, /\.game-picker\.is-worlds-open\s*\{[^}]*scroll-snap-type:\s*none/s)
assert.match(gameLibraryCss, /\.game-picker\s*\{[^}]*--game-card-width:\s*clamp\(230px, 23vw, 306px\)[^}]*padding:\s*38px max\(26px, calc\(\(100vw - var\(--game-card-width\)\) \/ 2\)\) 44px/s)
assert.match(gameLibraryCss, /\.game-picker\s*\{[^}]*--game-card-gap:\s*clamp\(18px, 2\.2vw, 30px\)/s)
assert.match(gameLibraryCss, /\.game-picker-item\s*\{[^}]*margin-right:\s*var\(--game-card-gap\)/s)
assert.match(gameLibraryCss, /\.game-picker-item--primary\s*\{[^}]*transition:\s*margin-right 360ms cubic-bezier\(0\.33, 0, 0\.67, 1\)/s)
assert.match(gameLibraryCss, /\.game-picker\.is-worlds-open:not\(\.is-worlds-closing\) \.game-picker-item--primary\s*\{[^}]*margin-right:\s*0[^}]*transition:\s*margin-right 360ms cubic-bezier\(0\.33, 0, 0\.67, 1\)/s)
assert.match(gameLibraryCss, /\.game-picker\.is-worlds-open\.is-worlds-closing \.game-picker-item--primary\s*\{[^}]*margin-right:\s*var\(--game-card-gap\)[^}]*transition:\s*margin-right 360ms cubic-bezier\(0\.33, 0, 0\.67, 1\)/s)
assert.match(gameLibraryCss, /url\('\/assets\/game-hub\/background_game_library_day_image2\.png'\)/)
assert.match(gameLibraryCss, /url\('\/assets\/game-hub\/background_game_library_image2\.png'\)/)
assert.match(gameLibraryCss, /\.game-hub--background-night\s*\{/)
assert.doesNotMatch(gameLibraryCss, /\.game-hub\s*\{[^}]*linear-gradient/s)
assert.match(gameLibraryCss, /\.game-hub-theme-toggle\s*\{[^}]*width:\s*44px[^}]*height:\s*44px/s)
assert.doesNotMatch(gameLibrarySource, /game-hub-brand-mark/)
assert.doesNotMatch(gameLibraryCss, /\.game-hub-brand-mark/)
assert.match(gameLibraryCss, /\.game-hub--library:not\(\.game-hub--background-night\) \.game-hub-topbar\s*\{[^}]*border-bottom-color:\s*transparent[^}]*background:\s*transparent[^}]*box-shadow:\s*none/s)
assert.match(gameLibraryCss, /\.game-hub--library\.game-hub--background-night \.game-hub-topbar\s*\{[^}]*border-bottom-color:\s*transparent[^}]*background:\s*transparent[^}]*box-shadow:\s*none/s)
assert.doesNotMatch(appSource, /RouteOrientationGuide|useMobileOrientation|requestMobileOrientation|screen\.orientation/)
assert.doesNotMatch(appRoutesSource, /AppRouteOrientation|appRouteOrientation/)
assert.doesNotMatch(appCss, /app-orientation-guide|screen\.orientation/)
assert.match(gameLibraryCss, /\.game-carousel-card\.is-selected\s*\{[^}]*transform:\s*scale\(1\.045\)/s)
assert.match(gameLibraryCss, /\.game-carousel-card\s*\{[^}]*grid-template-rows:\s*minmax\(0, 1fr\) auto[^}]*aspect-ratio:\s*1 \/ 1/s)
assert.match(gameLibraryCss, /\.game-carousel-cover\s*\{[^}]*aspect-ratio:\s*auto/s)
assert.match(gameLibraryCss, /url\('\/assets\/game-hub\/stardew-steam-store-header\.jpg'\) center \/ contain no-repeat/)
assert.match(gameLibraryCss, /\.game-carousel-card--not_installed \.game-carousel-cover[\s\S]*?filter:\s*grayscale\(1\)/)
assert.match(gameLibraryCss, /\.game-world-rail\s*\{[^}]*overflow:\s*clip[^}]*transition:\s*width 360ms cubic-bezier\(0\.33, 0, 0\.67, 1\)/s)
assert.match(gameLibraryCss, /\.game-world-rail\.is-open\.is-closing\s*\{[^}]*transition:\s*width 360ms cubic-bezier\(0\.33, 0, 0\.67, 1\)[^}]*opacity 240ms ease-in 70ms/s)
assert.match(gameLibraryCss, /\.game-world-rail-content\s*\{[^}]*transform:\s*translateX\(-42px\)/s)
assert.match(gameLibraryCss, /\.game-world-rail\.is-open \.game-world-rail-content\s*\{[^}]*transform:\s*translateX\(0\)[^}]*opacity 240ms ease-out 50ms[^}]*transform 360ms cubic-bezier\(0\.33, 0, 0\.67, 1\)/s)
assert.match(gameLibraryCss, /\.game-world-rail\.is-open\.is-closing \.game-world-rail-content\s*\{[^}]*opacity:\s*0[^}]*visibility:\s*visible[^}]*transform:\s*translateX\(-42px\)[^}]*opacity 240ms ease-in 70ms[^}]*transform 360ms cubic-bezier\(0\.33, 0, 0\.67, 1\)[^}]*visibility 0s linear 360ms/s)
assert.match(gameLibraryCss, /\.game-world-rail\.is-open \.world-choice-list li\s*\{[^}]*opacity:\s*1[^}]*transform:\s*translateX\(0\)[^}]*opacity 220ms ease-out 50ms[^}]*transform 360ms cubic-bezier\(0\.33, 0, 0\.67, 1\)/s)
assert.match(gameLibraryCss, /\.game-world-rail\.is-open\.is-closing \.world-choice-list li\s*\{[^}]*opacity:\s*0[^}]*transform:\s*translateX\(-50px\)[^}]*opacity 220ms ease-in 90ms[^}]*transform 360ms cubic-bezier\(0\.33, 0, 0\.67, 1\)/s)
assert.doesNotMatch(gameLibraryCss, /\.world-chooser-backdrop|\.world-chooser-panel/)
assert.match(gameLibraryCss, /@media\s*\(max-width:\s*700px\)[\s\S]*?\.game-picker\s*\{[^}]*--game-card-width:\s*min\(78vw, 320px\)[^}]*--game-card-gap:\s*0px[^}]*calc\(\(100vw - var\(--game-card-width\)\) \/ 2\)/)
assert.match(gameLibraryCss, /@media\s*\(max-width:\s*700px\)[\s\S]*?\.world-choice\s*\{[^}]*width:\s*min\(72vw, 240px\)/)
assert.match(gameLibraryCss, /\.world-create-card\s*\{[^}]*width:\s*clamp\(190px, 15vw, 210px\)[^}]*min-height:\s*0[^}]*aspect-ratio:\s*1 \/ 1[^}]*align-self:\s*center/s)
assert.match(gameLibraryCss, /@media\s*\(max-width:\s*700px\)[\s\S]*?\.world-create-card\s*\{[^}]*width:\s*min\(60vw, 232px\)/s)
assert.match(gameLibraryCss, /\.world-create-card--form\s*\{[^}]*width:\s*clamp\(238px, 18vw, 268px\)[^}]*min-height:\s*210px[^}]*aspect-ratio:\s*auto/s)
assert.match(gameLibraryCss, /\.world-create-field input\s*\{[^}]*min-height:\s*44px[^}]*font:\s*600 16px/s)
assert.match(gameLibraryCss, /\.world-create-form-actions button\s*\{[^}]*min-height:\s*44px/s)
assert.match(gameLibraryCss, /\.game-hub--background-night \.world-create-field input\s*\{[^}]*background:\s*rgba\(8, 26, 45, 0\.9\)/s)
assert.match(gameLibraryCss, /\.game-hub:not\(\.game-hub--background-night\) \.world-create-field input\s*\{[^}]*background:\s*rgba\(255, 249, 220, 0\.92\)/s)
assert.doesNotMatch(gameLibraryCss, /\.new-world-layout|\.new-world-form|\.new-world-receipt/)
assert.match(gameLibraryCss, /\.game-hub:not\(\.game-hub--background-night\) \.game-carousel-card\s*\{[^}]*background:\s*var\(--sd-card-bg\)/s)
assert.match(gameLibraryCss, /\.game-hub:not\(\.game-hub--background-night\) \.world-choice\s*\{[^}]*background:\s*var\(--sd-card-bg\)/s)
assert.match(gameLibraryCss, /\.game-hub:not\(\.game-hub--background-night\) \.world-create-card\s*\{[^}]*background:[^}]*var\(--sd-card-bg\)/s)
assert.match(gameLibraryCss, /\.game-hub:not\(\.game-hub--background-night\) \.game-carousel-card--soon \.game-carousel-cover\s*\{[^}]*background:[^}]*#dfe8c5/s)
assert.match(gameLibraryCss, /\.game-hub--background-night \.game-carousel-card\s*\{[^}]*background:\s*#17243b/s)
assert.match(gameLibraryCss, /\.game-hub--background-night \.world-choice\s*\{[^}]*background:\s*#17243b/s)
assert.match(gameLibraryCss, /\.game-hub--background-night \.world-create-card\s*\{[^}]*background:[^}]*#192842/s)
assert.doesNotMatch(gameLibraryCss, /\.game-world-rail-content::before/)
assert.match(gameLibraryCss, /\.game-hub--background-night \.world-choice-scene\s*\{[^}]*rgba\(20, 39, 77, 0\.2\)/s)
assert.match(gameLibraryCss, /\.world-copy-button\s*\{[^}]*width:\s*44px[^}]*height:\s*44px/s)
assert.match(gameLibraryCss, /\.world-copy-button,[\s\S]*?\.world-lifecycle-button\s*\{[^}]*min-height:\s*44px/s)
assert.match(gameLibraryCss, /\.world-lifecycle-button\s*\{[^}]*width:\s*100%/s)
assert.match(gameLibraryCss, /\.world-choice-heading\s*\{[^}]*min-height:\s*52px[^}]*flex-direction:\s*column/s, 'the status has its own row below the full-width name')
assert.match(gameLibraryCss, /\.world-choice-name\s*\{[^}]*-webkit-line-clamp:\s*1[^}]*overflow:\s*hidden[^}]*line-height:\s*1\.35/s, 'long names remain on one line without growing the card')
assert.match(gameLibraryCss, /\.world-name-row\s*\{[^}]*flex:\s*1[^}]*min-width:\s*0/s)
assert.match(gameLibraryCss, /\.world-name-editor\s*\{[^}]*grid-template-columns:\s*repeat\(2, minmax\(0, 1fr\)\)/s)
assert.match(gameLibrarySource, /className="world-choice-open"\s+title=\{worldName\}/, 'the full name remains available on hover and in the accessible label')
assert.match(gameLibraryCss, /\.world-choice-open:focus-visible\s*\{[^}]*outline-offset:\s*-5px/s)
assert.match(gameLibraryCss, /\.game-hub--background-night \.world-copy-button,[\s\S]*?background:\s*rgba\(9, 29, 53, 0\.82\)/)
assert.match(gameLibraryCss, /\.game-hub:not\(\.game-hub--background-night\) \.world-copy-button,[\s\S]*?background:\s*rgba\(255, 247, 215, 0\.78\)/)
assert.match(gameLibraryCss, /\.world-rail-message\s*\{[^}]*width:\s*154px[^}]*min-height:\s*350px/s)
assert.doesNotMatch(gameLibrarySource, /world-choice-disclosure/)
assert.doesNotMatch(gameLibraryCss, /\.world-choice-disclosure/)
assert.match(gameLibraryCss, /\.game-picker::-webkit-scrollbar\s*\{[^}]*display:\s*none/)
assert.match(gameLibraryCss, /@media\s*\(max-width:\s*700px\)[\s\S]*?scroll-margin-inline-start:\s*clamp\(28px, 10vw, 40px\)[\s\S]*?scroll-snap-align:\s*start/)
assert.match(gameLibraryCss, /@media\s*\(max-width:\s*700px\) and \(orientation:\s*portrait\)[\s\S]*?\.game-hub--library\s*\{[^}]*position:\s*fixed[^}]*width:\s*100dvh[^}]*height:\s*100dvw[^}]*transform:\s*rotate\(90deg\) translateY\(-100%\)[^}]*transform-origin:\s*top left/s)
assert.match(gameLibraryCss, /@media\s*\(max-width:\s*700px\) and \(orientation:\s*portrait\)[\s\S]*?\.game-hub--library \.game-picker\s*\{[^}]*calc\(\(100dvh - var\(--game-card-width\)\) \/ 2\)/s)
assert.match(gameLibraryCss, /@media\s*\(max-width:\s*700px\) and \(orientation:\s*portrait\)[\s\S]*?\.game-hub--library \.world-create-card--form\s*\{[^}]*width:\s*clamp\(214px, 58dvw, 236px\)[^}]*min-height:\s*190px/s)
assert.match(gameLibraryCss, /@media\s*\(max-width:\s*900px\) and \(max-height:\s*520px\) and \(orientation:\s*landscape\)/)
assert.match(gameLibraryCss, /@media\s*\(max-width:\s*900px\) and \(max-height:\s*520px\) and \(orientation:\s*landscape\)[\s\S]*?\.world-create-card--form\s*\{[^}]*width:\s*clamp\(214px, 58dvh, 236px\)[^}]*min-height:\s*190px/s)
assert.match(gameLibraryCss, /@media\s*\(prefers-reduced-motion:\s*reduce\)[\s\S]*?\.game-carousel-card\.is-selected\s*\{[^}]*transform:\s*none/s)
assert.match(appSource, /appRoute\.kind === 'games' \|\| appRoute\.kind === 'stardew-worlds' \|\| appRoute\.kind === 'stardew-new-world' \|\| appRoute\.kind === 'stardew-install'[\s\S]*?worldsOpen=\{appRoute\.kind === 'stardew-worlds' \|\| appRoute\.kind === 'stardew-new-world'\}[\s\S]*?installOpen=\{appRoute\.kind === 'stardew-install'\}/)
assert.doesNotMatch(appSource, /StardewGlobalInstallPage/)
assert.match(gameLibrarySource, /<GameInstallRail[\s\S]*?requestedInstallJobId=\{requestedInstallJobId\}[\s\S]*?onPresentationChange=\{onInstallPresentationChange\}/)
assert.match(gameLibrarySource, /className=\{`game-card-progress-ring is-\$\{installPresentation\.mode\}[\s\S]*?--game-install-progress/)
assert.match(gameInstallRailSource, /<span>Steam 账号<\/span>/)
assert.match(gameInstallRailSource, />Steam 密码<\/label>/)
assert.match(gameInstallRailSource, />VNC 密码<\/label>/)
assert.match(gameInstallRailSource, /type=\{steamPasswordVisible \? 'text' : 'password'\}/)
assert.match(gameInstallRailSource, /type=\{vncPasswordVisible \? 'text' : 'password'\}/)
assert.ok(gameInstallRailSource.includes("aria-label={`${steamPasswordVisible ? '隐藏' : '显示'} Steam 密码`}"))
assert.ok(gameInstallRailSource.includes("aria-label={`${vncPasswordVisible ? '隐藏' : '显示'} VNC 密码`}"))
assert.match(gameInstallRailSource, /installInstance\(\{ steamUsername, steamPassword, vncPassword \}, targetId\)/)
assert.match(gameInstallRailSource, /canonicalInstallPageJobs\([\s\S]*?requestedInstallJobId/)
assert.match(gameInstallRailSource, /getLatestJobLogs\(jobId, 1000\)/)
assert.match(gameInstallRailSource, /aria-label="当前安装步骤进度"/)
assert.match(gameInstallRailSource, /const automaticChoice = phase === 'auth_method_required'[\s\S]*?phase === 'steamcmd_guard_choice_required'/)
assert.match(gameInstallRailSource, /submitSteamGuardInput\(jobId, '1', targetId\)/)
assert.doesNotMatch(gameInstallRailSource, />扫码登录<|选择 Steam 登录方式|选择 Steam Guard 验证方式/)
assert.match(gameInstallRailSource, /setEditingCredentials\(true\)[\s\S]*?setJobId\(null\)[\s\S]*?onNavigate\(routeToPath\('install', undefined, targetId\), true\)/)
const inlineInstallSubmit = gameInstallRailSource.slice(gameInstallRailSource.indexOf('async function submitInstall('), gameInstallRailSource.indexOf('async function submitGuard('))
assert.doesNotMatch(inlineInstallSubmit, /set(?:SteamUsername|SteamPassword|VncPassword)\(''\)/, 'successful job creation must preserve the editable retry draft in memory')
assert.match(gameInstallRailSource, /presentation\.mode !== 'complete'[\s\S]*?setSteamUsername\(''\)[\s\S]*?setSteamPassword\(''\)[\s\S]*?setVncPassword\(''\)/)
assert.match(gameInstallRailSource, /const indeterminate = taskActive && presentation\.percent === null/)
assert.match(gameInstallRailSource, /<b>\{progressLabel\}<\/b>/)
assert.doesNotMatch(gameInstallRailSource, /localStorage|sessionStorage/, 'credential drafts must not be persisted in browser storage')
assert.match(installProgressPresentationSource, /extractPullProgress[\s\S]*?extractSMAPIArchiveProgress[\s\S]*?extractSteamDownloadProgress/)
assert.match(installProgressPresentationSource, /percent: progress\?\.percent \?\? null/)
assert.match(gameLibraryCss, /\.game-carousel-card::after\s*\{[^}]*inset:\s*-3px;[^}]*border:\s*3px solid transparent;/s)
assert.match(gameLibraryCss, /\.game-card-progress-ring\s*\{[\s\S]*?conic-gradient\([\s\S]*?var\(--game-install-ring-color\) 0 var\(--game-install-progress\)/)
assert.match(gameLibraryCss, /\.game-card-progress-ring\s*\{[^}]*inset:\s*-4px;[^}]*padding:\s*4px;/s)
assert.match(gameLibrarySource, /installPresentation\.overallPercent \* 3\.6/)
assert.match(gameLibrarySource, /aria-label="总体安装进度"[\s\S]*?aria-valuenow=\{installPresentation\.overallPercent\}/)
assert.match(gameLibrarySource, /总进度/)
assert.doesNotMatch(gameLibraryCss, /game-install-ring-sweep|game-install-ring-spin|--game-install-ring-angle/)
assert.doesNotMatch(gameLibrarySource, /game-card-progress-ring[^\n]*is-indeterminate/)
assert.match(gameLibraryCss, /\.game-install-auth-choice \.game-install-inline-action button\s*\{[^}]*min-height:\s*58px;/s)
assert.match(gameLibraryCss, /\.game-install-password-toggle\s*\{[^}]*width:\s*44px;[^}]*height:\s*44px;/s)
assert.match(gameLibraryCss, /\.game-install-secret-control input\s*\{[^}]*padding-right:\s*50px;/s)
assert.match(gameLibraryCss, /@media\s*\(prefers-reduced-motion:\s*reduce\)[\s\S]*?\.game-install-progress-bar[\s\S]*?animation:\s*none/)
assert.match(qaSource, /INSTALL_QA = params\.get\('installQa'\)/)
assert.match(qaSource, /INSTALL_QA === 'auth-method' \? 'auth_method_required' : 'game_downloading'/)
assert.ok(qaSource.includes("/\\/api\\/instances\\/[^/]+\\/install$/"))
assert.match(qaSource, /\/api\\\/instances\\\/\[\^\/\]\+\\\/\(start\|stop\)\$[\s\S]*?qaLibraryLifecycleState = stopping \? 'stopping' : 'starting'/)
assert.match(qaSource, /INSTANCE_CATALOG === 'single'[\s\S]*?\[baseInstanceListFixture\[0\]\]/)
assert.doesNotMatch(appSource, /<StardewNewWorldPage|StardewNewWorldPage,/)
assert.match(instanceIdSource, /export let activeInstanceId = FALLBACK_INSTANCE_ID/)
assert.match(instanceIdSource, /export function setActiveInstanceId/)
assert.match(apiSource, /export \{ activeInstanceId as defaultInstanceId \} from '.\/instance-id\.ts'/)
assert.match(apiSource, /export function setDefaultInstanceId/)
assert.match(appSource, /const resolvedDefaultInstanceId = setDefaultInstanceId\(status\.defaultInstanceId\)[\s\S]*?if \(!status\.initialized\)/)
assert.match(jobsLogsPageSource, /getLatestJobLogs\(selectedJobId\)/)
assert.match(jobsLogsPageSource, /const jobRes = await getJob\(selectedJobId\)\s+const logsRes = await getLatestJobLogs\(selectedJobId\)/)
assert.match(jobsLogsPageSource, /setLogsTruncated\(logsRes\.hasEarlier\)/)
assert.match(jobsLogsPageSource, /当前显示最新 1000 行日志，更早的日志未加载。/)
assert.doesNotMatch(jobsLogsPageSource, /当前仅显示最近加载的 1000 行日志/)
assert.match(newGameCreatorCss, /@container\s+ngc-modal\s*\(max-width:\s*1100px\)[\s\S]{0,260}grid-template-columns:minmax\(205px,\.9fr\) minmax\(360px,1\.75fr\) minmax\(172px,\.78fr\)/)
assert.match(newGameCreatorCss, /@container\s+ngc-modal\s*\(max-width:\s*780px\)[\s\S]{0,220}grid-template-columns:minmax\(205px,\.82fr\) minmax\(0,1\.7fr\)/)
assert.match(newGameCreatorCss, /@container\s+ngc-modal\s*\(max-width:\s*780px\)[\s\S]{0,360}grid-column:1\s*\/\s*-1/)
assert.match(newGameCreatorCss, /@container\s+ngc-modal\s*\(max-width:\s*560px\)[\s\S]{0,180}grid-template-columns:minmax\(0,1fr\)/)
assert.match(newGameCreatorCss, /@container\s+ngc-modal\s*\(max-width:\s*480px\)/)
assert.match(newGameCreatorCss, /@container\s+ngc-modal\s*\(max-width:\s*360px\)/)
assert.doesNotMatch(newGameCreatorCss, /@container\s+ngc-modal\s*\(max-width:\s*1100px\)[\s\S]{0,260}grid-template-columns:\s*1fr/)
assert.doesNotMatch(newGameCreatorCss, /transform:\s*scale\(/)
assert.doesNotMatch(newGameCreatorCss, /@container\s+sd-main-scroll/)
assert.match(playersPageSource, /sd-players-pending-table-row/)
assert.match(playersPageCss, /\.sd-players-pending-table\s*{[^}]*overflow-x:\s*hidden/s)
assert.match(playersPageCss, /\.sd-players-pending-table \.sd-players-pending-table-row\s*{[^}]*grid-template-columns:[^}]*min-width:\s*0/s)
assert.match(modalPortalSource, /createPortal/)
assert.match(modalPortalSource, /document\.body/)
assert.match(modalPortalSource, /event\.key !== 'Tab'/)
assert.match(modalPortalSource, /event\.key === 'Escape'/)
assert.match(modalPortalSource, /returnTarget\.focus\(\)/)
assert.match(modalPortalSource, /element\.inert = true/)
assert.match(modalPortalSource, /setAttribute\('aria-hidden', 'true'\)/)
for (const modalConsumer of [
  panelSource,
  savesSectionSource,
  settingsPageSource,
  jobsLogsPageSource,
  playersPageSource,
  modsPageSource,
  mobileControlPageSource,
  mobileSavesPageSource,
]) {
  assert.match(modalConsumer, /<ModalPortal/)
}
assert.match(savesSectionSource, /role="alertdialog"/)
assert.match(mobileControlPageSource, />\s*填入\s*</)
assert.match(serverControlPageSource, /<PlayerAuthSettingsDialog/)
assert.match(mobileControlPageSource, /<PlayerAuthSettingsDialog/)
assert.match(playerAuthDialogSource, /mode:\s*'none'/)
assert.match(playerAuthDialogSource, /mode:\s*'global'/)
assert.match(playerAuthDialogSource, /mode:\s*'role'/)
assert.match(playerAuthDialogSource, /getInstancePlayerAuthConfig/)
assert.match(playerAuthDialogSource, /updateInstancePlayerAuthConfig/)
assert.doesNotMatch(playerAuthDialogSource, /restartInstance/)
assert.match(playerAuthDialogSource, /onRestart:\s*\(\) => Promise<void>/)
assert.match(playerAuthDialogSource, /!restartSettingChanged\s*&&\s*!roleCredentialsChanged/)
assert.match(playerAuthDialogSource, /revisionChanged\s*&&\s*next\.restartRequired\s*&&\s*isRunning/)
assert.match(playerAuthDialogSource, /await onRestart\(\)[\s\S]*?onClose\(\)/)
assert.match(serverControlPageSource, /onRestart={handleRestart}/)
assert.match(mobileControlPageSource, /onRestart={onPlayerAuthRestart}/)
assert.match(compactShellSource, /restartInProgress[\s\S]*?'正在重启'/)
assert.match(compactShellSource, /onPlayerAuthRestart={lifecycleActions\.handleRestart}/)
assert.match(lifecycleActionsSource, /restartInProgress\s*=\s*pendingStartupAction\s*===\s*'restart'/)
assert.match(lifecycleActionsSource, /pendingStartupSawActiveJob/)
assert.match(lifecycleActionsSource, /refreshInstanceState\(\)[\s\S]*?refreshJobs\(\)/)
assert.match(modsPageSource, /const latest = await loadMods\(\)[\s\S]*?syncNexusResultsFromInstalledMods\(latest\.mods\)/)
assert.match(diagnosticsPageSource, /Promise\.allSettled\([\s\S]*?getHealthDiagnostics\(\)[\s\S]*?getComposePs\(\)[\s\S]*?healthResult\.status === 'fulfilled'[\s\S]*?composeResult\.status === 'fulfilled'/)
assert.match(jobsLogsPageSource, /selectedStillExists[\s\S]*?setSelectedJob\(null\)[\s\S]*?setLogs\(\[\]\)/)
assert.match(mobileSavesPageSource, /setBackups\(Array\.isArray\(result\.backups\) \? result\.backups : \[\]\)/)
assert.match(stardewRoutesSource, /refreshMods: \(\) => Promise<void>/)
assert.match(stardewRoutesSource, /refreshPublicIP: \(\) => Promise<void>/)
assert.match(playerAuthDialogSource, /role="alertdialog"/)
assert.match(playerAuthDialogSource, /timeoutSeconds/)
assert.match(playerAuthDialogSource, /maxAttempts/)
assert.match(playerAuthDialogSource, /htmlFor={`\$\{dialogTitleId\}-timeout`}/)
assert.match(playerAuthDialogSource, /htmlFor={`\$\{dialogTitleId\}-attempts`}/)
assert.match(playerAuthDialogSource, /mode !== 'none' \? <fieldset className="sd-player-auth-policy-fields"/)
assert.match(playerAuthDialogSource, /credentialStatus/)
assert.match(playerAuthDialogSource, /rolePasswordRemovals/)
assert.match(playerAuthDialogSource, /第一次 !login/)
assert.doesNotMatch(playerAuthDialogSource, /启用前必须/)
for (const password of ['x', 'one internal space', '不间断\u00a0空格', '🔐'.repeat(128)]) {
  assert.equal(playerAuthPasswordError(password, '角色密码'), null, `valid role password rejected: ${password}`)
}
for (const password of ['', ' leading', 'trailing ', 'two  spaces', 'line\nbreak', '🔐'.repeat(129)]) {
  assert.notEqual(playerAuthPasswordError(password, '角色密码'), null, `invalid role password accepted: ${password}`)
}
assert.match(playerAuthDialogCss, /\.sd-player-auth-modes\s*{[^}]*grid-template-columns:\s*repeat\(3,/s)
assert.match(playerAuthDialogCss, /@media\s*\(max-width:\s*620px\)[\s\S]*?\.sd-player-auth-modes\s*{[^}]*grid-template-columns:\s*1fr/s)
assert.match(playerAuthDialogCss, /\.sd-player-auth-role-list\s*{[^}]*overflow-y:\s*auto/s)
assert.match(playerAuthDialogCss, /\.sd-player-auth-clear\.sd-mctrl-dialog-btn\s*{[^}]*min-height:\s*44px/s)
assert.match(playerAuthDialogCss, /\.sd-player-auth-policy-fields\s*{[^}]*grid-template-columns:\s*repeat\(2,/s)
assert.match(playerAuthDialogCss, /@media\s*\(max-width:\s*620px\)[\s\S]*?\.sd-player-auth-policy-fields\s*{[^}]*grid-template-columns:\s*1fr/s)
assert.match(jobsLogsPageSource, /CONTROL_COMMAND_PAGE_SIZE\s*=\s*3/)
assert.match(jobsLogsPageSource, /controlCommands\.slice\(/)
assert.match(jobsLogsPageSource, /aria-label="最近控制命令分页"/)
assert.match(qaSource, /cmd_qa_joja_07/)
assert.match(modsPageSource, /typeof ResizeObserver === 'undefined'/)
assert.match(diagnosticsPageSource, /sd-diag-header-actions[\s\S]*?导出诊断包[\s\S]*?重新检查[\s\S]*?<\/div>/)
assert.match(diagnosticsPageSource, /sd-diag-maintenance-tools">\s*<p>[\s\S]*?<\/p>\s*<\/div>/)
assert.match(diagnosticsPageCss, /@media\s*\(max-width:\s*760px\)[\s\S]*?\.sd-diag-page \.sd-diag-header-actions\s*{[^}]*grid-template-columns:\s*repeat\(2,/s)
assert.match(diagnosticsPageCss, /@media\s*\(max-width:\s*460px\)[\s\S]*?\.sd-diag-page \.sd-diag-header-actions\s*{[^}]*grid-template-columns:\s*1fr/s)
assert.match(
  modsPageCss,
  /\.sd-mods-nexus-card \.sd-mods-card-actions > \.sd-btn-delete\s*{[^}]*background-color:\s*transparent;[^}]*color:\s*#fff5d6;/s,
)
assert.match(qaSource, /SURFACE === 'app'/)
assert.match(qaSource, /\/\\\/control-commands\$\//)
assert.match(qaSource, /\/\\\/config\\\/player-auth\$\//)
assert.match(qaSource, /timeoutSeconds:\s*120/)
assert.match(qaSource, /maxAttempts:\s*5/)
assert.match(releaseGates, /npm run test:responsive-layout/)
assert.match(compatibilityWorkflow, /npm run test:responsive-layout/)
assert.match(releaseGates, /npm run test:new-game-idempotency/)
assert.match(compatibilityWorkflow, /npm run test:new-game-idempotency/)
assert.match(releaseGates, /npm run test:nexus-extension-idempotency/)
assert.match(compatibilityWorkflow, /npm run test:nexus-extension-idempotency/)
assert.match(releaseGates, /npm run test:cabin-strategy-options/)
assert.match(compatibilityWorkflow, /npm run test:cabin-strategy-options/)
assert.match(releaseGates, /npm run test:runtime-player-limit/)
assert.match(compatibilityWorkflow, /npm run test:runtime-player-limit/)
assert.match(releaseGates, /npm run test:save-backup-details/)
assert.match(compatibilityWorkflow, /npm run test:save-backup-details/)
assert.match(releaseCandidateScript, /assert_frontend_contract_from_container/)
assert.match(releaseCandidateScript, /ServerRuntimeSettingsDialog/)
assert.match(releaseCandidateScript, /FarmhouseStack（兼容已有配置）/)
assert.match(releaseCandidateScript, /game-day rollback hover details/)
assert.match(releaseUpgradeE2E, /assert_upgraded_frontend_contract/)
assert.match(releaseUpgradeE2E, /ServerRuntimeSettingsDialog/)
assert.match(releaseUpgradeE2E, /FarmhouseStack（兼容已有配置）/)
assert.match(releaseUpgradeE2E, /game-day rollback hover details/)
assert.ok(releaseCandidateWorkflow.includes('scripts/run-release-gates.sh'))
// This fork removed the push trigger from the release-candidate pipeline: it builds
// and validates a candidate against the upstream image namespaces and needs upstream
// secrets and CI capacity, so it failed on every push to main. It is manual-only
// here, and this fork's own image is published by fork-image.yml.
assert.ok(!releaseCandidateWorkflow.includes('push:\n    branches: [main]'))
assert.ok(releaseCandidateWorkflow.includes('workflow_dispatch:'))
assert.ok(releaseCandidateWorkflow.includes('oldest_version:'))
assert.ok(releaseCandidateWorkflow.includes('Validate affected oldest supported Web upgrade'))
assert.ok(releaseCandidateWorkflow.includes('candidate-oldest.json'))
assert.ok(releaseCandidateWorkflow.includes('[manual-release-candidate]'))
assert.ok(releaseCandidateWorkflow.includes("github.event_name != 'push'"))
assert.ok(releaseCandidateWorkflow.includes('scripts/validate-release-matrix.sh'))
assert.ok(releaseCandidateWorkflow.includes('--require-oldest-for-zero-patch'))
assert.ok(releaseAfterCandidateWorkflow.includes('workflow_run:'))
assert.ok(releaseAfterCandidateWorkflow.includes('gh workflow run release.yml'))
assert.ok(releaseAfterCandidateWorkflow.includes("workflow_run.event != 'push'"))
assert.ok(releaseAfterCandidateWorkflow.includes('workflow_run.head_commit.message'))
assert.ok(releaseAfterCandidateWorkflow.includes('.previousVersion // empty'))
assert.ok(releaseAfterCandidateWorkflow.includes('.oldestTestedVersion // empty'))
assert.ok(releaseAfterCandidateWorkflow.includes('--require-oldest-for-zero-patch'))
assert.ok(releaseWorkflow.includes('workflow_dispatch:'))
assert.ok(releaseWorkflow.includes('.previousVersion // empty'))
assert.ok(releaseWorkflow.includes('.oldestTestedVersion // empty'))
assert.ok(releaseWorkflow.includes('--require-oldest-for-zero-patch'))
assert.match(releaseWorkflow, /skopeo copy --all --preserve-digests/)
assert.doesNotMatch(releaseWorkflow, /docker build/)
for (const workflowSource of [releaseCandidateWorkflow, releaseAfterCandidateWorkflow]) {
  assert.ok(workflowSource.includes('if [[ "$previous" != "$latest_release" ]]; then'))
}
assert.ok(releaseWorkflow.includes('group: release-panel-promotion'))
assert.ok(releaseWorkflow.includes('echo "previous=$previous"'))
assert.ok(releaseWorkflow.includes('if [[ "$previous" != "$latest_release" && "$version" != "$latest_release" ]]; then'))
assert.ok(releaseAfterCandidateWorkflow.includes('tag_candidate_run_id'))
assert.ok(releaseAfterCandidateWorkflow.includes('bound to a different or malformed immutable candidate'))
assert.ok(releaseAfterCandidateWorkflow.includes('git tag -a "$tag" "$commit" -m "$tag validated candidate" -m "Candidate workflow: $CANDIDATE_RUN_ID"'))
assert.ok(releaseAfterCandidateWorkflow.includes('Digest: $digest'))
assert.ok(releaseWorkflow.includes('echo "tag_candidate_run_id=$tag_candidate_run_id"'))
assert.ok(releaseWorkflow.includes('echo "tag_candidate_digest=$tag_candidate_digest"'))
assert.ok(releaseWorkflow.includes('actions/runs/$TAG_CANDIDATE_RUN_ID/artifacts'))
assert.ok(releaseWorkflow.includes('.conclusion == "success" and .head_sha == $sha and .head_branch == "main" and .path == ".github/workflows/release-candidate.yml"'))
assert.ok(releaseWorkflow.includes('[.artifacts[] | select(.name == $name and (.expired | not))] | length'))
assert.ok(releaseWorkflow.includes('if [[ "$artifact_count" != 1 ]]; then'))
assert.ok(releaseWorkflow.includes('"$digest" != "$TAG_CANDIDATE_DIGEST"'))
assert.doesNotMatch(releaseWorkflow, /actions\/workflows\/release-candidate\.yml\/runs/)
assert.ok(releaseWorkflow.includes('git fetch --no-tags origin main:refs/remotes/origin/main'))
const identityMainFetch = releaseWorkflow.indexOf('git fetch --no-tags origin main:refs/remotes/origin/main')
const identityMainRead = releaseWorkflow.indexOf('git rev-parse origin/main')
assert.ok(identityMainFetch >= 0 && identityMainRead > identityMainFetch)
assert.ok(releaseWorkflow.includes('origin/main changed after exact version promotion'))
assert.ok(releaseWorkflow.includes('latest GitHub Release changed after proof validation'))
const latestPromotionStep = releaseWorkflow.indexOf('- name: Promote and verify latest tags')
const latestMainRecheck = releaseWorkflow.indexOf('git fetch --no-tags origin main:refs/remotes/origin/main', latestPromotionStep)
const latestReleaseRecheck = releaseWorkflow.indexOf(`latest_release="$(gh api "repos/$GITHUB_REPOSITORY/releases/latest" --jq '.tag_name')"`, latestPromotionStep)
const firstLatestCopy = releaseWorkflow.indexOf('docker://$DOCKERHUB_IMAGE:latest', latestPromotionStep)
assert.ok(latestPromotionStep >= 0
  && latestMainRecheck > latestPromotionStep
  && latestReleaseRecheck > latestMainRecheck
  && firstLatestCopy > latestReleaseRecheck)
assert.ok(releaseMatrixValidator.includes('oldest version must be strictly older than previous version'))
assert.ok(releaseMatrixValidator.includes('an affected oldest version is required for an explicit zero-patch release'))
assert.match(releaseMatrixValidator, /0\.6\.0\)[\s\S]*?"\$previous_version" != "0\.5\.13"[\s\S]*?"\$oldest_version" != "0\.3\.2"/)
assert.ok(releaseMatrixTests.includes('--version 0.6.0 --previous-version 0.5.13 --oldest-version 0.3.2 --require-oldest-for-zero-patch'))
assert.ok(releaseGates.includes('bash scripts/tests/test_release_matrix.sh'))

console.log('responsive layout tests passed')
